[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_stake_pool = "stQo8YUfVZG49VJ3Ewt9mzZBG3KFk9EkrBKJugc2d6J"

[programs.devnet]
cardinal_stake_pool = "stQo8YUfVZG49VJ3Ewt9mzZBG3KFk9EkrBKJugc2d6J"

[programs.testnet]
cardinal_stake_pool = "stQo8YUfVZG49VJ3Ewt9mzZBG3KFk9EkrBKJugc2d6J"

[programs.localnet]
cardinal_stake_pool = "stQo8YUfVZG49VJ3Ewt9mzZBG3KFk9EkrBKJugc2d6J"
